"""Pydantic models for PlanVantage API request/response objects."""

from planvantage.models.base import PlanVantageModel
from planvantage.models.plansponsor import (
    PlanSponsorCreateRequest,
    PlanSponsorData,
    PlanSponsorInfo,
    PlanSponsorUpdateRequest,
)
from planvantage.models.scenario import (
    CalculateAllOptionsRequest,
    ClaimScenarioRequest,
    ClaimScenarioResponse,
    CreateScenarioFromPlanDocumentRequest,
    CreateScenarioFromPlanDocumentResponse,
    ImportScenarioRequest,
    ScenarioCreateRequest,
    ScenarioData,
    ScenarioHistoryInput,
    ScenarioInfo,
    ScenarioTierNameSetInput,
    ScenarioUpdateRequest,
    ScenarioUpdateResponse,
    ShareScenarioEmailResult,
    ShareScenarioRequest,
    ShareScenarioResponse,
    SyncEnrollmentRequest,
)
from planvantage.models.plandesign import (
    CopyPlanDesignRequest,
    PlanAvResultData,
    PlanDesignData,
    PlanDesignTierData,
    PlanDesignTierUtilizationData,
    PlanDesignUtilizationData,
    PlanModelSettingsData,
    ServiceCostShareData,
)
from planvantage.models.rateplan import (
    CopyCurrentRatePlanRequest,
    HSAMethod,
    RateMethod,
    RateModelAssumptionsData,
    RateModelSettingsData,
    RatePlanAdjustmentData,
    RatePlanAdjustmentInput,
    RatePlanData,
    RatePlanInput,
    RatePlanTierData,
    RatePlanTierInput,
    RatePlanTierNameData,
    TierNameSetData,
    TierNameSetInput,
)
from planvantage.models.contribution import (
    ContributionGroupCriteria,
    ContributionGroupData,
    ContributionOptionData,
    ContributionOptionImportItem,
    ContributionOptionItem,
    ContributionOptionItemsLists,
    ContributionPlanData,
    ContributionTierData,
    ContributionTierEnrollmentUpdateData,
    PlanSponsorItems,
    ProposedContributionGroupData,
    ProposedContributionGroupInput,
    ProposedContributionOptionStatusData,
    ProposedContributionTierData,
    ProposedContributionTierEnrollmentUpdate,
    ProposedContributionTierInput,
    ScenarioOptionItems,
)
from planvantage.models.plandocument import (
    PlanDocumentData,
    PlanDocumentInfo,
    PlanDocumentInput,
)
from planvantage.models.user import LimitedUserInput
from planvantage.models.census import (
    AmbiguousColumnCandidate,
    AmbiguousColumnsInfo,
    ApplyCensusEnrollmentResult,
    CensusColumnMetadata,
    CensusData,
    CensusFilterRule,
    CensusInfo,
    CensusMappingConfig,
    CensusMappingFilters,
    CensusMappingInfo,
    CensusMappingValidation,
    CensusOptOutMapping,
    CensusParticipationAdjustment,
    CensusPlanMapping,
    CensusSchemaConfig,
    CensusSubgroup,
    CensusSubgroupConfig,
    CensusTemplateConfig,
    CensusTierMapping,
    CensusUploadResult,
    CensusValidationError,
    ColumnNullDefault,
    EnrollmentSummary,
    MigrationChange,
    MigrationEstimation,
    MigrationPreviewResponse,
    PIIDetection,
    PlanEnrollmentPreview,
    ScenarioCensusInfo,
    StoredMigrationResponse,
)
from planvantage.models.exhibit import (
    ContributionOptionInfo,
    ExhibitApplyContributionInput,
    ExhibitColumnData,
    ExhibitData,
    ExhibitFixedCostCellData,
    ExhibitFixedCostReorderInput,
    ExhibitFixedCostRowData,
    ExhibitFixedCostRowInput,
    ExhibitInfo,
    ExhibitInput,
    ExhibitPEPMInput,
    ExhibitScenarioConfigData,
    ExhibitScenarioInput,
    ExhibitScenarioUpdateInput,
    ExhibitSettingsData,
    ExhibitTableData,
    ExhibitUpdateInput,
    FixedCostLineItemData as _ExhibitFixedCostLineItemData,
    SummaryContributionData,
)
from planvantage.models.summary import (
    FixedCostLineItemData,
    FixedCostLineItemInput,
    ImportFixedCostLineItemsInput,
    MoveDirectionInput,
    SummaryData,
    SummarySettingsData,
    SummaryTotalsData,
    ToggleAutoCalcInput,
)
# NOTE: The following models are intentionally excluded:
# - AIModelResponse (aimodel.py) - internal use only
# - ApiKeyData, ApiKeyCreateResponse (apikey.py) - managed via web UI only

__all__ = [
    # Base
    "PlanVantageModel",
    # PlanSponsor
    "PlanSponsorInfo",
    "PlanSponsorData",
    "PlanSponsorCreateRequest",
    "PlanSponsorUpdateRequest",
    # Scenario
    "ScenarioInfo",
    "ScenarioData",
    "ScenarioCreateRequest",
    "ScenarioUpdateRequest",
    "ScenarioUpdateResponse",
    "ScenarioTierNameSetInput",
    "ScenarioHistoryInput",
    "SyncEnrollmentRequest",
    "CalculateAllOptionsRequest",
    "ImportScenarioRequest",
    "CreateScenarioFromPlanDocumentRequest",
    "CreateScenarioFromPlanDocumentResponse",
    "ShareScenarioRequest",
    "ShareScenarioResponse",
    "ShareScenarioEmailResult",
    "ClaimScenarioRequest",
    "ClaimScenarioResponse",
    # PlanDesign
    "PlanDesignData",
    "PlanDesignTierData",
    "ServiceCostShareData",
    "PlanAvResultData",
    "PlanModelSettingsData",
    "PlanDesignUtilizationData",
    "PlanDesignTierUtilizationData",
    "CopyPlanDesignRequest",
    # RatePlan
    "RatePlanInput",
    "RatePlanTierInput",
    "RatePlanData",
    "RatePlanTierData",
    "RatePlanAdjustmentData",
    "RatePlanAdjustmentInput",
    "RateModelSettingsData",
    "RateModelAssumptionsData",
    "RateMethod",
    "HSAMethod",
    "RatePlanTierNameData",
    "TierNameSetData",
    "TierNameSetInput",
    "CopyCurrentRatePlanRequest",
    # Contribution
    "ContributionTierData",
    "ContributionPlanData",
    "ContributionGroupData",
    "ContributionGroupCriteria",
    "ContributionOptionData",
    "ContributionTierEnrollmentUpdateData",
    "ContributionOptionItem",
    "ContributionOptionImportItem",
    "ScenarioOptionItems",
    "PlanSponsorItems",
    "ContributionOptionItemsLists",
    "ProposedContributionGroupData",
    "ProposedContributionGroupInput",
    "ProposedContributionTierData",
    "ProposedContributionTierInput",
    "ProposedContributionTierEnrollmentUpdate",
    "ProposedContributionOptionStatusData",
    # PlanDocument
    "PlanDocumentInfo",
    "PlanDocumentData",
    "PlanDocumentInput",
    # User
    "LimitedUserInput",
    # Census
    "CensusInfo",
    "CensusData",
    "CensusSchemaConfig",
    "CensusColumnMetadata",
    "ColumnNullDefault",
    "CensusMappingConfig",
    "CensusMappingInfo",
    "CensusMappingFilters",
    "CensusFilterRule",
    "CensusMappingValidation",
    "CensusPlanMapping",
    "CensusTierMapping",
    "CensusOptOutMapping",
    "CensusSubgroup",
    "CensusSubgroupConfig",
    "CensusParticipationAdjustment",
    "CensusTemplateConfig",
    "CensusUploadResult",
    "CensusValidationError",
    "PIIDetection",
    "ScenarioCensusInfo",
    "AmbiguousColumnCandidate",
    "AmbiguousColumnsInfo",
    "MigrationChange",
    "MigrationEstimation",
    "PlanEnrollmentPreview",
    "EnrollmentSummary",
    "MigrationPreviewResponse",
    "StoredMigrationResponse",
    "ApplyCensusEnrollmentResult",
    # Exhibit
    "ExhibitInfo",
    "ExhibitData",
    "ExhibitScenarioConfigData",
    "ExhibitInput",
    "ExhibitUpdateInput",
    "ExhibitScenarioInput",
    "ExhibitScenarioUpdateInput",
    "ExhibitApplyContributionInput",
    "ExhibitColumnData",
    "ExhibitFixedCostCellData",
    "ExhibitFixedCostRowData",
    "ExhibitTableData",
    "ExhibitFixedCostRowInput",
    "ExhibitFixedCostReorderInput",
    "ExhibitPEPMInput",
    "ExhibitSettingsData",
    "ContributionOptionInfo",
    # Summary & FixedCost
    "SummaryData",
    "SummaryTotalsData",
    "SummaryContributionData",
    "SummarySettingsData",
    "FixedCostLineItemData",
    "FixedCostLineItemInput",
    "ImportFixedCostLineItemsInput",
    "ToggleAutoCalcInput",
    "MoveDirectionInput",
]
